- id: 200
  key: satoshi
  currency: btc
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 400
  key: bank
  currency: jpy
  fixed: 2
  fee_max: 0
  min: 100
  max: 50000
  fee: 0.003
  proportion: true
  inuse: true
  type: WithdrawChannelBank
- id: 800
  key: ethereum
  currency: eth
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelEthereum
- id: 1000
  key: ripple
  currency: xrp
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelRipple
- id: 2000
  key: ethereumclassic
  currency: etc
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelEthereumClassic
- id: 3000
  key: bitcoincash
  currency: bch
  fixed: 8
  fee: 0
  inuse: true
  type: WithdrawChannelBitcoincash
- id: 4000
  key: kuberacoin
  currency: kbr
  fixed: 8
  fee: 0
  inuse: true
  type: WithdrawChannelKuberacoin
- id: 5000
  key: bitcoingold
  currency: btg
  fixed: 8
  fee: 0
  inuse: true
  type: WithdrawChannelBitcoingold